let
    Source = Data,
    #"Removed Other Columns" = Table.SelectColumns(Source,{"Date"}),
    #"Calculated Latest" = List.Max(#"Removed Other Columns"[Date]),
    #"Calculated End of Year" = Date.EndOfYear(#"Calculated Latest")
in
    #"Calculated End of Year"